FROM php:8.3
RUN apt-get update \
    && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    git
RUN docker-php-ext-install zip pdo pdo_mysql
WORKDIR /api
COPY . /api

# INSTALLCOMPOSER
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# INSTALL DEPENDENCIES
RUN COMPOSER_ALLOW_SUPERUSER=1
RUN composer install

EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]